version: "3"
services:
  ## Server .Net6.0
  dotnetclean:
    image: dotnetclean
    container_name: dotnetclean
    build:
      context: ./Api/Boardgame/
      dockerfile: Dockerfile.dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=host.docker.internal;Initial Catalog=BoardGameData; User Id=sa; Password=mssql1234;
    ports:
      - "8000:8000"
    volumes:
      - ./Api/Boardgame/Boardgame.Api/:/app/Boardgame.Api
      - ./Api/Boardgame/Boardgame.Contracts/:/app/Boardgame.Contracts
      - ./Api/Boardgame/Boardgame.Infrastructure/:/app/Boardgame.Infrastructure
      - ./Api/Boardgame/Boardgame.Application/:/app/Boardgame.Application
      - ./Api/Boardgame/Boardgame.Domain/:/app/Boardgame.Domain

  # Web client boardgame
  webapp:
    build:
      context: ./frontend
      target: dev
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/src:/app/src

  ## Web client webadmin
  webadmin:
    build:
      context: ./webadmin
      target: dev
    ports:
      - "5000:5000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./webadmin/src:/app/src
