# POST http://localhost:8000/api/work/add
POST http://localhost:5107/api/work/add/e4d756fa-ce1c-46cc-8cb8-ba08712c6708
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0OGYyMzBkNS01ZjIzLTQ1ZGQtOWE4Yy0wMTdjZGUxNmY1YmYiLCJnaXZlbl9uYW1lIjoiQ2hhbnl1dCIsImp0aSI6ImQ5NzNiZjBiLTI1ZGUtNDk4Mi05NDU2LTJmMDk3NDRjNGU0ZiIsInJvbGUiOiJHTSIsImV4cCI6MTcwODUxODM2OCwiaXNzIjoiQm9hcmRHYW1lQXBwIiwiYXVkIjoiQm9hcmRHYW1lQXBwIn0.3QwzhqcacFs_XC9W8KbnVQubjW47II7XebulQvVYSv0