POST http://localhost:8000/api/authentication/forgetpassword-sentemail
# POST http://localhost:5107/api/authentication/forgetpassword-sentemail
Content-Type: application/json

# {
#     "email": "sohetem872@laymro.com"
# }

{
    "email": "chanyut0986071813@gmail.com"
}