# POST http://localhost:8000/api/authentication/login
POST http://localhost:5107/api/authentication/login
Content-Type: application/json

{
    "email": "chanyut281144",
    "password": "$chanyutD01Admin"
}

# {
#     "email": "chanyut0986071813@gmail.com",
#     "password": "$chanyutD01"
# }

# {
#     "email": "sohetem872@laymro.com",
#     "password": "$chanyutD22"
# }

# {
#     "email": "rakeka3945@ebuthor.com",
#     "password": "$chanyutD01"
# }