# POST http://localhost:8000/api/authentication/login
POST http://localhost:5107/api/authentication/login
Content-Type: application/json

{
    "email": "chanyut@gmail.com",
    "password": "112244"
}