
POST http://localhost:5107/api/authentication/gm/register-gm
# POST http://localhost:8000/api/authentication/gm/register-gm
# Admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMDMxOGU5Zi03MDUzLTRjODItNmY5Yy0wOGRjM2Q3MjY1YjMiLCJnaXZlbl9uYW1lIjoiQWRtaW4iLCJqdGkiOiJlOTAzYzRlOC0yNDNmLTQ3M2ItOWE0MC0xMGQzYTQ0NmNmYWYiLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDk2ODQyNTgsImlzcyI6IkJvYXJkR2FtZUFwcCIsImF1ZCI6IkJvYXJkR2FtZUFwcCJ9.QItSxvY7RCQe2XavalGorl6PomA3koRCt5jCyAPH4Xk

{
    "name": "Chanyut",
    "email": "chanyut0986071813@gmail.com",
    "phoneNumber": "0985541245",
    "password": "$chanyutD01",
    "confirmPassword": "$chanyutD01"
}

# {
#     "name": "Rakeka",
#     "email": "rakeka3945@ebuthor.com",
#     "phoneNumber": "0822659456",
#     "password": "$chanyutD01",
#     "confirmPassword": "$chanyutD01"
# }