
POST http://localhost:5107/api/authentication/gm/register-gm
# POST http://localhost:8000/api/authentication/gm/register-gm
# Admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMDMxOGU5Zi03MDUzLTRjODItNmY5Yy0wOGRjM2Q3MjY1YjMiLCJnaXZlbl9uYW1lIjoiQWRtaW4iLCJqdGkiOiI0MjljOGYxZi00N2QzLTRmMjEtOWJhZS04ZjIzZWNiZDg2NzQiLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MTAxMDI5MjMsImlzcyI6IkJvYXJkR2FtZUFwcCIsImF1ZCI6IkJvYXJkR2FtZUFwcCJ9.nDZCXthbZJgyerjs7HOSg7XQp7y1pZk6T9YV_i1aD4s

{
    "name": "TempMail",
    "email": "casere3229@comsb.com",
    "phoneNumber": "0985541245",
    "password": "$chanyutD01",
    "confirmPassword": "$chanyutD01"
}

# {
#     "name": "Rakeka",
#     "email": "rakeka3945@ebuthor.com",
#     "phoneNumber": "0822659456",
#     "password": "$chanyutD01",
#     "confirmPassword": "$chanyutD01"
# }