POST http://localhost:5107/api/authentication/resetpassword
Content-Type: application/json

{
    "email": "sohetem872@laymro.com",
    "token": "Q2ZESjhMazZlakR2UkExRW5GS0lBWm00WUJIcE5Ba1hUdytOaXRPK0pUMXhUcnRXVTFwN25CMnBEUEJmRUlnZ2wxL3lwTTB1M0xIaFdpM2FqSGJJSEJjYjUrOWtMcUxwU1VIaXAzYzNJdWVLTFdQSThvbmpZcmhnSlJCMm9BZzNhRkJCWGh6NEdYRW14d2hTeXc1Y3NxMWoyMnF3R1NNejJRYU1CV3kyUVZqSThuNVJLU1lHZVhPcWJEd1pMRjBXRytUR3krVDBvMVc1N0R3NnFQZ3BSMDJFbjdRNitrZDdyL2ZOenhuWlpuMHRzeHRF",
    "password": "$chanyutD22",
    "confirmPassword": "$chanyutD22"
}