POST http://localhost:5107/api/scansystem/get-scanByCard
# POST http://localhost:8000/api/scansystem/get-scanByCard
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0OGYyMzBkNS01ZjIzLTQ1ZGQtOWE4Yy0wMTdjZGUxNmY1YmYiLCJnaXZlbl9uYW1lIjoiQ2hhbnl1dCIsImp0aSI6ImUyODllMWU4LWI3ZTctNGU3YS04MTE3LTk1NzkxMGJhZjczMyIsInJvbGUiOiJHTSIsImV4cCI6MTcwODgxMDMwNCwiaXNzIjoiQm9hcmRHYW1lQXBwIiwiYXVkIjoiQm9hcmRHYW1lQXBwIn0.42Q9jFqx7IYP823gJVWulZUUlhlWK0eMq4O-nlAcrU4

{
    "cardId": "EA47422B-C745-4C24-AFE9-402A5C402969"
}