GET http://localhost:5107/api/gm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMDMxOGU5Zi03MDUzLTRjODItNmY5Yy0wOGRjM2Q3MjY1YjMiLCJnaXZlbl9uYW1lIjoiQWRtaW4iLCJqdGkiOiI3MjEzMjllNS00OTYxLTQ5ZDUtYWNlYi1iNDViNjYwODYzOGEiLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MTAwODkyMDYsImlzcyI6IkJvYXJkR2FtZUFwcCIsImF1ZCI6IkJvYXJkR2FtZUFwcCJ9.Jh-h95NKAFVhHhvv3hrq_QNyaesmT2pC69BgttVS6CY
