GET http://localhost:5107/api/test
# GET http://localhost:8000/api/test
# Member
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNmQzMzA1ZC01Njk1LTRjYmUtODQwMC02MzNjZDczNmY1YTQiLCJnaXZlbl9uYW1lIjoiVGVtcCIsImVtYWlsIjoic29oZXRlbTg3MkBsYXltcm8uY29tIiwianRpIjoiMmVkZmIyNmUtYmU0YS00YWJiLWIxMTItYWVjNzMzMGI0NmVlIiwicm9sZSI6Ik1FTUJFUiIsImV4cCI6MTcwODI0MTMyNywiaXNzIjoiQm9hcmRHYW1lQXBwIiwiYXVkIjoiQm9hcmRHYW1lQXBwIn0.9Ttc3OEdJdCOqgKFzjw-5tbWnaFdHtbAHyavg_cwYgE